### ISSUE TITLE
Getting too much data from Plex-server...

### ISSUE THREAD

**Issue by Snille** [Gyran/MMM-plex-recently-added#1]
Hi! I'm trying out your nice module, but I have a rather large collection on my Plex-server. And it looks like the module just goes crazy downloading all the covers from the "section" (either Movies or TV-Series).
I've made a short move here: https://youtu.be/6giB8fyMiKs
Sorry for the bad sound quality. :)

**Comment by Gyran** [comment]
Woha, that's a lot. Just committed something now that might fix it. Haven't had time to test it thoroughly. But please test it and see if it helps.

**Comment by Snille** [comment]
Working! Thank you! :)
