### ISSUE TITLE
Broken after latest update

### ISSUE THREAD

**Issue by sunkast** [Gyran/MMM-plex-recently-added#8]
No clue what changed, but now the module doesn't function correctly. Console has this error:

MMM-plex-recently-added: No items found for movie, check Plex Token

I double checked the token and it is perfectly fine. The module shows me my latest movies, but not my latest TV shows. So nothing is wrong with the token.

How to fix?

**Comment by sunkast** [comment]
Found the issue. The library section IDs for my PMS are apparently not the same as the ones hard coded into node_helper.js on lines 19-22.

```
const PlexTypes = {
  [Types.MOVIE]: '1',
  [Types.TV]: '2'
}
```

Changing the numbers to 2 for movie, and 3 for tv worked to select both tv and movies from my Plex. This part of the code should not be hard coded as clearly there is a circumstance where the library IDs for TV and Movie are not 1 and 2.

Perhaps there is a more intelligent way to determine and call the correct library IDs for TV and Movie? @zzarbi Any ideas?

**Comment by Gyran** [comment]
Weird.. Looks like we did the same before
```
var TYPE_MAP = {
  [TYPES.MOVIE]: '1',
  [TYPES.EPISODE]: '2',
  [TYPES.SEASON]: '2',
};
```

How does your config look?

**Comment by sunkast** [comment]
```
     module: 'MMM-plex-recently-added',
     position: 'top_center',
     config: {
        token: '',
		hostname: '',
		limit: 10,
		displayType: 'mixed',
```

Token and IP removed for privacy of course. Really not sure why it works now after changing the types to 2, 3.

If I call `http://ip:32400/library/sections/1/recentlyAdded/?X-Plex-Token=token` it comes up as 404. But changing the 1 to 2 or 3, I get just a blank page. Not sure why it works changing the types. I only discovered this poking around at the library section IDs to see if I could reconstruct the URL being called to try and troubleshoot the issue.

**Comment by Gyran** [comment]
Found the error, will have a new version up in a few min!

**Comment by Gyran** [comment]
@sunkast can you try it now and see how it works?

**Comment by sunkast** [comment]
That works! Thank you for looking into and fixing this so quickly!
